### ISSUE TITLE
isTrigger collision

### ISSUE THREAD

**Issue by bubbaboogs** [Another-Axiom/GorillaLocomotion#20]
When a collider is set to isTrigger I can still collide with it.

**Comment by biotest05** [comment]
put the layer to another one cuz the enabled locomotion layer is to default

**Comment by bubbaboogs** [comment]
> put the layer to another one cuz the enabled locomotion layer is to default

It still doesn't work.

**Comment by bubbaboogs** [comment]
Thanks, it works now.
