### ISSUE TITLE
What is the "Surface" Script?

### ISSUE THREAD

**Issue by TheTechWiz5305** [Another-Axiom/GorillaLocomotion#33]
What is it and what is it used for?

**Comment by caden3ds** [comment]
It's supposed to be for slippery surfaces but it's broken

**Comment by Ultrasnowy543** [comment]
It's For The Friction On A Surface It Basically Is The Amount That Your Hand Will Slide Around
Lets Say It's 0.5 Then Your Hand Will Move Around On The Surface It's Touching Multiplied By 0.5 So It Will Be Half Friction
Let's Say It's 0 Then Your Hand Will Not Slide Around At All It Will Stick In Place
Although This Does Not Affect How Your Player Gets Moved So Your Hand Will Still Move You The Same And It Does Not Have Gravity
Gorilla Locomotion Is Unique But This Is A Very Old Version Of It This Is From When Gorilla Tag Was First Released In Beta
When The Stump Still Had Pegs For A Way Up And There Was No Canyons Or Caves When There Was No City Or Hats Room When There Was No Slippery Walls When There Was No Cosmetics When There Was Only 1 Hitsound For Everything
Thats Why This Locomotion Is Not The Same As Gorilla Tag In It's Current State

**Comment by CanyonsEcho** [comment]
theres a better script with the new slippery system by dev, it also has built in hitsounds and slide sounds
