### ISSUE TITLE
Hands are sticking to the floor like there is glue everywhere

### ISSUE THREAD

**Issue by TheTechWiz5305** [Another-Axiom/GorillaLocomotion#35]
Hello! Whenever I move, it's like glue is all over the floor, because the hands are always sticking to the floor. Is there any way to fix it? Settings and Video are provided below.

[Video](https://github.com/Another-Axiom/GorillaLocomotion/assets/132825368/25d91b35-4c6a-4c00-9918-f4e8810b4f39)

![image](https://github.com/Another-Axiom/GorillaLocomotion/assets/132825368/10dde7de-9575-48af-89fe-9f2d96f69761)
![image](https://github.com/Another-Axiom/GorillaLocomotion/assets/132825368/00ed6d97-355a-4175-a83b-ca5dc2fd33ea)
![image](https://github.com/Another-Axiom/GorillaLocomotion/assets/132825368/fd7166bc-666e-4c2a-b268-e7fd5f7d5a59)

**Comment by JulerGaming** [comment]
I found a solution

Where it says Interpulate set that to none.
This should fix your "floor glue" issue.

**Comment by TheTechWiz5305** [comment]
I'll try that. Thank you!

**Comment by FlegmonTheDuck** [comment]
> I found a solution
> 
> Where it says Interpulate set that to none. This should fix your "floor glue" issue.

LEGENDARY UNDERRATED COMMENT
