### ISSUE TITLE
Movement broken when changing fixed timestep in unity 2022

### ISSUE THREAD

**Issue by ghost** [Another-Axiom/GorillaLocomotion#46]
when you change the fixed timestep you can barely jump and its just the default scene from gorilla locomotion does anyone know how to fix this unity 2021 is gonna lose support soon and from what i have seen unity 2022 has better performance and more futures to use does anyone know how to fix it

**Comment by LexLeoo** [comment]
if anyone has the same problem after changing the fixed timestep i was using unity 2022 unity changed how they do there physics so when i switched to the latest LTS from 2021 it fixed if anyone knows how to fix it in unity 2022 can you comment and say how
